# Yamllint configuration
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
    indent-sequences: true
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .venv/
  venv/
  node_modules/
  vendor/
  .git/